let mySet = new Set()
let aMap = new Map()
aMap.set('hi', 'there')
mySet.add(1)
mySet.add(2)
mySet.add(4)
mySet.add(2)
mySet.add(false)
mySet.add({ hankus : 'says-hello' })
mySet.add(aMap)
console.log(mySet)
mySet.forEach((item) => {
    console.log(item)
})
console.log(mySet.values())
console.log(mySet.keys())
console.log(mySet.has(1))
console.log(mySet.size)