const myMap = new Map()
myMap.set("hi", "henry")
myMap.set("hello", "there")
console.log(myMap, myMap.size)
myMap.forEach((entry) => {
    console.log(entry)
})
console.log('Get keys: ', myMap.keys())
console.log('Get values: ', myMap.values())
myMap.delete('hi')
console.log(myMap)
console.log(myMap.has('hello'))
console.log(myMap.size)